### ISSUE TITLE
[SmartReact] Reaction adding exception

### ISSUE THREAD

**Issue by kpopdev** [ptoast/FlapJack-Cogs#123]
await self._state.http.add_reaction(self.channel.id, self.id, emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 10014): Unknown Emoji
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\candy\cogs\CogManager\cogs\smartreact\sm
artreact.py", line 125, in on_message
    await message.add_reaction(emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\message.py", line 994, in add_reaction
    await self._state.http.add_reaction(self.channel.id, self.id, emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 10014): Unknown Emoji
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\candy\cogs\CogManager\cogs\smartreact\sm
artreact.py", line 125, in on_message
    await message.add_reaction(emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\message.py", line 994, in add_reaction
    await self._state.http.add_reaction(self.channel.id, self.id, emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 10014): Unknown Emoji
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\candy\cogs\CogManager\cogs\smartreact\sm
artreact.py", line 125, in on_message
    await message.add_reaction(emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\message.py", line 994, in add_reaction
    await self._state.http.add_reaction(self.channel.id, self.id, emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 10014): Unknown Emoji
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\candy\cogs\CogManager\cogs\smartreact\sm
artreact.py", line 125, in on_message
    await message.add_reaction(emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\message.py", line 994, in add_reaction
    await self._state.http.add_reaction(self.channel.id, self.id, emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 10014): Unknown Emoji
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\candy\cogs\CogManager\cogs\smartreact\sm
artreact.py", line 125, in on_message
    await message.add_reaction(emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\message.py", line 994, in add_reaction
    await self._state.http.add_reaction(self.channel.id, self.id, emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 10014): Unknown Emoji
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\candy\cogs\CogManager\cogs\smartreact\sm
artreact.py", line 125, in on_message
    await message.add_reaction(emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\message.py", line 994, in add_reaction
    await self._state.http.add_reaction(self.channel.id, self.id, emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 10014): Unknown Emoji

**Comment by aikaterna** [comment]
I was unable to repro your issue even though it looks like it was missing an emoji that it could previously see. There are changes in bbaef99, please update and see if that fixes your issue.

**Comment by kpopdev** [comment]
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\candy\cogs\CogManager\cogs\smartreact\smartreact.py", line 136, in on_message
    await message.add_reaction(emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\message.py", line 994, in add_reaction
    await self._state.http.add_reaction(self.channel.id, self.id, emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 10014): Unknown Emoji
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\candy\cogs\CogManager\cogs\smartreact\smartreact.py", line 136, in on_message
    await message.add_reaction(emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\message.py", line 994, in add_reaction
    await self._state.http.add_reaction(self.channel.id, self.id, emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 10014): Unknown Emoji
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\candy\cogs\CogManager\cogs\smartreact\smartreact.py", line 136, in on_message
    await message.add_reaction(emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\message.py", line 994, in add_reaction
    await self._state.http.add_reaction(self.channel.id, self.id, emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 10014): Unknown Emoji
Ignoring exception in on_message
Traceback (most recent call last):
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\client.py", line 333, in _run_event
    await coro(*args, **kwargs)
  File "C:\Users\Administrator\AppData\Local\Red-DiscordBot\Red-DiscordBot\data\candy\cogs\CogManager\cogs\smartreact\smartreact.py", line 136, in on_message
    await message.add_reaction(emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\message.py", line 994, in add_reaction
    await self._state.http.add_reaction(self.channel.id, self.id, emoji)
  File "C:\Users\Administrator\redenv\lib\site-packages\discord\http.py", line 245, in request
    raise HTTPException(r, data)
discord.errors.HTTPException: 400 Bad Request (error code: 10014): Unknown Emoji

it spam this still after i update.

**Comment by aikaterna** [comment]
Thanks for working with me on this. You can find the changes that you have already tested, on 02013fe.
