### ISSUE TITLE
[bigmoji] Error when trying to load cog

### ISSUE THREAD

**Issue by chrys-the-flower** [ptoast/FlapJack-Cogs#149]
Hi,
I'm trying to load the bigmoji cog but keep getting the response

```
Failed to load the following package: bigmoji.
Check your console or logs for details.
```

Here are the details from my console logs:

```
[2023-07-19 09:26:52] [ERROR] red: Package loading failed
Traceback (most recent call last):
  File "/data/venv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 188, in _load
    await bot.load_extension(spec)
  File "/data/venv/lib/python3.11/site-packages/redbot/core/bot.py", line 1686, in load_extension
    await lib.setup(self)
TypeError: object NoneType can't be used in 'await' expression
```

**Comment by aikaterna** [comment]
Install the repo and cog(s) you're using from the Red 3.5 compatible branch instead: https://github.com/flapjax/FlapJack-Cogs/tree/red-v3-dpy2
