### ISSUE TITLE
[wordclouds] Broken on Red 3.5.3 / discord.py 2.3.1

### ISSUE THREAD

**Issue by Technetium1** [ptoast/FlapJack-Cogs#150]
> Failed to load the following package: `wordclouds`.
Check your console or logs for details.

```py
Exception during loading of package:

Traceback (most recent call last):
  File "{HOME}/redenv/lib/python3.11/site-packages/redbot/core/core_commands.py", line 188, in _load
    await bot.load_extension(spec)
  File "{HOME}/redenv/lib/python3.11/site-packages/redbot/core/bot.py", line 1686, in load_extension
    await lib.setup(self)
TypeError: object NoneType can't be used in 'await' expression
```
Relevant info:
- Python 3.11.3
- discord.py 2.3.1
- Arch Linux

**Comment by aikaterna** [comment]
Install the repo and the cog from the Red 3.5 compatible branch instead, https://github.com/flapjax/FlapJack-Cogs/tree/red-v3-dpy2
