### ISSUE TITLE
Bigmoji and wand vs cairosvg

### ISSUE THREAD

**Issue by aikaterna** [ptoast/FlapJack-Cogs#99]
Using bigmoji on a server that doesn't have cairosvg installed leads it to fall back to using wand for svg conversion, which fails on default, non-custom emojis. I believe this is because it's expecting a BytesIO object and it's getting a string of some sort. While I don't expect this to be an issue with many devices besides perhaps Windows (cairosvg is notoriously difficult to install on some Windows versions), I wanted to report it in case someone would like to get to it someday. Cairosvg is also in the cog's requirements in the info.json so theoretically we should never see this issue from someone.

```
[2019-06-25 17:18:39] [ERROR] red: Exception in command 'bigmoji'
Traceback (most recent call last):
  File "/root/.local/share/catv3/lib/python3.7/site-packages/discord/ext/commands/core.py", line 63, in wrapped
    ret = await coro(*args, **kwargs)
  File "/root/.local/share/Red-DiscordBot/cogs/CogManager/cogs/bigmoji/bigmoji.py", line 93, in bigmoji
    await ctx.send(file=discord.File(img, name))
  File "/root/.local/share/catv3/lib/python3.7/site-packages/discord/file.py", line 68, in __init__
    self.fp = open(fp, 'rb')
ValueError: embedded null byte
```

**Comment by Kovaelin** [comment]
I'm getting "Emoji not found." whether I have cairosvg installed or not for default emojis like :zero: or :cloud_tornado:

**Comment by aikaterna** [comment]
Please open a new issue next time but your comment has been resolved with 5dbfd48
